name: Deploy to production
on:
  push:
    branches:
      - production
jobs:
  Deploy to production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use node version 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.3'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install gatsby CLI
        run: npm install -g gatsby-cli
      - name: Build gatsby resources
        run: gatsby build
      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          local-dir: './public/'
          server-dir: 'www/pinafrica.org/'
          dry-run: false
          log-level: verbose
