name: CI

on:
  push:
    branches-ignore:
      - development
Jobs:
  - name: Deploy to server
    id: deploy
    uses: Pendect/action-rsyncer@v1.1.0
    env:
      DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
    with:
      flags: '-avzr --delete'
      options: ''
      ssh_options: ''
      src: 'public/'
      dest: 'user@server.com:/var/www/server.com'

  - name: Display status from deploy
    run: echo "${{ steps.deploy.outputs.status }}"
