name: CI

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: pinafrica.org
          FTP_USERNAME: ${{secrets.DEPLOY_USER}}
          FTP_PASSWORD: ${{ secrets.DEPLOY_KEY }}
          LOCAL_DIR: public/
          REMOTE_DIR: /var/www/html/development/
#         ARGS: --delete
