name: CI

on:
  push:
    branches-ignore:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: "-avzr"
          options: ""
          ssh_options: ""
          src: "public/"
          dest: "benson@pinafrica.org:/var/www/html/staging/"
      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
